# Generated by Django 6.0.5 on 2026-06-11 17:24

import django.db.models.deletion
from django.db import migrations, models


def legacy_assignment_upload_path(instance, filename):
    return f'assignments/legacy/{instance.student_id}/{filename}'


def legacy_validate_assignment_file(_uploaded_file):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_assignment_assignmentsubmission'),
        ('students', '0006_student_programme_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Text answer'), ('file_upload', 'File upload'), ('both', 'Text + File upload')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=legacy_assignment_upload_path, validators=[legacy_validate_assignment_file]),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
