# Generated by Django 6.0.5 on 2026-06-11 20:30

import django.db.models.deletion
from django.db import migrations, models


def map_legacy_assignment_types(apps, schema_editor):
    Assignment = apps.get_model('enrollments', 'Assignment')
    Assignment.objects.filter(submission_type__in=['text', 'file_upload', 'both']).update(
        submission_type='practical',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_assignmentsubmission_graded_at_and_more'),
    ]

    operations = [
        migrations.RunPython(map_legacy_assignment_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='uploaded_file_name',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='quiz_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('quiz', 'Quiz assessment'), ('practical', 'Practical assessment')], default='quiz', max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='enrollments.assignment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
