# Generated by Django 6.0.5 on 2026-08-06 19:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_assignment_public_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_max_score', models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('practical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_project_max_score', models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('final_project_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('objective_quiz_max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('objective_quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_project_feedback', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('below_pass_mark', 'Below pass mark'), ('certificate_issued', 'Certificate issued')], default='incomplete', max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessment_results', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='enrollments.enrollment')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
