# Generated by Django 6.0.5 on 2026-05-15 00:00
from django.db import migrations, models


def populate_receipt_numbers(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    counters = {}
    for payment in Payment.objects.order_by('created_at', 'id'):
        receipt_year = payment.year or (
            payment.payment_date.year if payment.payment_date else payment.created_at.year
        )
        counters[receipt_year] = counters.get(receipt_year, 0) + 1
        payment.receipt_number = f'VTA-{receipt_year}-{counters[receipt_year]:06d}'
        payment.save(update_fields=['receipt_number'])


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0002_payment_month_year_payment_date_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(populate_receipt_numbers, migrations.RunPython.noop),
    ]
