# Generated by Codex on 2026-05-19
from django.db import migrations, models


def normalize_payment_statuses(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='completed').update(status='paid')
    Payment.objects.filter(status='refunded').update(status='failed')


def restore_legacy_payment_statuses(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='paid').update(status='completed')


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0003_payment_receipt_number'),
    ]

    operations = [
        migrations.RunPython(normalize_payment_statuses, restore_legacy_payment_statuses),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
