# Generated by Codex on 2026-05-19
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0004_payment_status_paid_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash', 'Cash'),
                    ('mobile_money', 'Mobile Money'),
                    ('card', 'Card'),
                    ('bank_transfer', 'Bank Transfer'),
                    ('paystack', 'Paystack'),
                ],
                max_length=20,
            ),
        ),
    ]
