# Generated by Django 6.0.5 on 2026-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='approval_status',
        ),
    ]
