# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_student_course_certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(
                choices=[
                    ('participation', 'Participation'),
                    ('completion', 'Completion'),
                    ('excellence', 'Excellence'),
                ],
                default='completion',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(
                fields=('student', 'course'),
                name='unique_student_course_certificate',
            ),
        ),
    ]
