# Generated by Django 6.0.1 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificatebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
