# Generated by Django 6.0.5 on 2026-08-06 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_pass_mark',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
